### ISSUE TITLE
Need delete bad feature

### ISSUE THREAD

**Issue by Max-RM** [misode/vscode-nbt#40]
the new version cannot open the NBT file without internet while the old version 0.6.8 can work without internet.

Btw I can use it on Android
![Screenshot_2023-01-23-10-58-38-244_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/213984092-dd5b16ea-4a1d-4e3a-8016-a0e4267a2e7d.jpg)

**Comment by misode** [comment]
Assets are no longer packaged with the extension, they are fetched from [mcmeta](https://github.com/misode/mcmeta/). This was a required change in order to support multiple versions.

The first time you open a structure made in a certain version it will do a web request, but the results are cached so you will be able to use the extension without a connection in the future for the same versions.
