### ISSUE TITLE
In the nbt rewrite branch you can only edit nbt data of files that dont have entities

### ISSUE THREAD

**Issue by RatDonkeyGoat** [misode/vscode-nbt#41]
https://github.com/misode/vscode-nbt/tree/nbt-rewrite

in this branch 

as an example it will edit this file
[abandonedlibrary.zip](https://github.com/misode/vscode-nbt/files/10529525/abandonedlibrary.zip)

but will not edit this file
[cart.zip](https://github.com/misode/vscode-nbt/files/10529526/cart.zip)

**Comment by misode** [comment]
Does this also happen in the latest release version?

**Comment by oakelope** [comment]
You can't edit files at all on the version that is on vscode

**Comment by oakelope** [comment]
Unless I was doing something wrong

**Comment by misode** [comment]
@RatDonkeyGoat How are you testing the nbt-reqrite branch? Are you building it yourself from source? In case you're using the beta version I had published a few months ago, that one was a bit broken and there have been changes since.

I cannot reproduce the issue on the current commit. I can open and edit both of your files fine.

**Comment by misode** [comment]
@oakelope Can you open another issue for this and supply as much information as you can?

**Comment by RatDonkeyGoat** [comment]
uh sure but the issue still persists with the version you just sent

**Comment by RatDonkeyGoat** [comment]
also i am oakelope just different github on my phone for some reason sorry for confusion
